=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module DigitalCovidCertificateClient
  class QRName
    # Surname(s) of person tested
    attr_accessor :fn

    # The forename(s) of the person addressed in certificate
    attr_accessor :gn

    # ICAO 9303 transilerated surname
    attr_accessor :fnt

    # ICAO 9303 transilerated forename
    attr_accessor :gnt

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'fn' => :'fn',
        :'gn' => :'gn',
        :'fnt' => :'fnt',
        :'gnt' => :'gnt'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'fn' => :'String',
        :'gn' => :'String',
        :'fnt' => :'String',
        :'gnt' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DigitalCovidCertificateClient::QRName` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DigitalCovidCertificateClient::QRName`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'fn')
        self.fn = attributes[:'fn']
      end

      if attributes.key?(:'gn')
        self.gn = attributes[:'gn']
      end

      if attributes.key?(:'fnt')
        self.fnt = attributes[:'fnt']
      end

      if attributes.key?(:'gnt')
        self.gnt = attributes[:'gnt']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @fn.nil?
        invalid_properties.push('invalid value for "fn", fn cannot be nil.')
      end

      if @gn.nil?
        invalid_properties.push('invalid value for "gn", gn cannot be nil.')
      end

      if @fnt.nil?
        invalid_properties.push('invalid value for "fnt", fnt cannot be nil.')
      end

      pattern = Regexp.new(/^[A-Z<]*$/)
      if @fnt !~ pattern
        invalid_properties.push("invalid value for \"fnt\", must conform to the pattern #{pattern}.")
      end

      if @gnt.nil?
        invalid_properties.push('invalid value for "gnt", gnt cannot be nil.')
      end

      pattern = Regexp.new(/^[A-Z<]*$/)
      if @gnt !~ pattern
        invalid_properties.push("invalid value for \"gnt\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @fn.nil?
      return false if @gn.nil?
      return false if @fnt.nil?
      return false if @fnt !~ Regexp.new(/^[A-Z<]*$/)
      return false if @gnt.nil?
      return false if @gnt !~ Regexp.new(/^[A-Z<]*$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] fnt Value to be assigned
    def fnt=(fnt)
      if fnt.nil?
        fail ArgumentError, 'fnt cannot be nil'
      end

      pattern = Regexp.new(/^[A-Z<]*$/)
      if fnt !~ pattern
        fail ArgumentError, "invalid value for \"fnt\", must conform to the pattern #{pattern}."
      end

      @fnt = fnt
    end

    # Custom attribute writer method with validation
    # @param [Object] gnt Value to be assigned
    def gnt=(gnt)
      if gnt.nil?
        fail ArgumentError, 'gnt cannot be nil'
      end

      pattern = Regexp.new(/^[A-Z<]*$/)
      if gnt !~ pattern
        fail ArgumentError, "invalid value for \"gnt\", must conform to the pattern #{pattern}."
      end

      @gnt = gnt
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          fn == o.fn &&
          gn == o.gn &&
          fnt == o.fnt &&
          gnt == o.gnt
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [fn, gn, fnt, gnt].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DigitalCovidCertificateClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
