=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module DigitalCovidCertificateClient
  class TestManf
    N308 = "308".freeze
    N344 = "344".freeze
    N345 = "345".freeze
    N768 = "768".freeze
    N770 = "770".freeze
    N1065 = "1065".freeze
    N1097 = "1097".freeze
    N1114 = "1114".freeze
    N1144 = "1144".freeze
    N1162 = "1162".freeze
    N1173 = "1173".freeze
    N1178 = "1178".freeze
    N1180 = "1180".freeze
    N1190 = "1190".freeze
    N1197 = "1197".freeze
    N1199 = "1199".freeze
    N1200 = "1200".freeze
    N1201 = "1201".freeze
    N1215 = "1215".freeze
    N1216 = "1216".freeze
    N1218 = "1218".freeze
    N1223 = "1223".freeze
    N1225 = "1225".freeze
    N1228 = "1228".freeze
    N1232 = "1232".freeze
    N1236 = "1236".freeze
    N1242 = "1242".freeze
    N1243 = "1243".freeze
    N1244 = "1244".freeze
    N1253 = "1253".freeze
    N1257 = "1257".freeze
    N1263 = "1263".freeze
    N1266 = "1266".freeze
    N1267 = "1267".freeze
    N1268 = "1268".freeze
    N1271 = "1271".freeze
    N1278 = "1278".freeze
    N1286 = "1286".freeze
    N1295 = "1295".freeze
    N1296 = "1296".freeze
    N1304 = "1304".freeze
    N1319 = "1319".freeze
    N1324 = "1324".freeze
    N1331 = "1331".freeze
    N1333 = "1333".freeze
    N1341 = "1341".freeze
    N1343 = "1343".freeze
    N1347 = "1347".freeze
    N1353 = "1353".freeze
    N1357 = "1357".freeze
    N1360 = "1360".freeze
    N1363 = "1363".freeze
    N1365 = "1365".freeze
    N1375 = "1375".freeze
    N1392 = "1392".freeze
    N1420 = "1420".freeze
    N1437 = "1437".freeze
    N1443 = "1443".freeze
    N1456 = "1456".freeze
    N1457 = "1457".freeze
    N1465 = "1465".freeze
    N1466 = "1466".freeze
    N1468 = "1468".freeze
    N1481 = "1481".freeze
    N1484 = "1484".freeze
    N1485 = "1485".freeze
    N1489 = "1489".freeze
    N1490 = "1490".freeze
    N1494 = "1494".freeze
    N1495 = "1495".freeze
    N1501 = "1501".freeze
    N1573 = "1573".freeze
    N1574 = "1574".freeze
    N1581 = "1581".freeze
    N1599 = "1599".freeze
    N1604 = "1604".freeze
    N1606 = "1606".freeze
    N1610 = "1610".freeze
    N1618 = "1618".freeze
    N1654 = "1654".freeze
    N1689 = "1689".freeze
    N1691 = "1691".freeze
    N1722 = "1722".freeze
    N1736 = "1736".freeze
    N1739 = "1739".freeze
    N1747 = "1747".freeze
    N1751 = "1751".freeze
    N1759 = "1759".freeze
    N1762 = "1762".freeze
    N1763 = "1763".freeze
    N1764 = "1764".freeze
    N1767 = "1767".freeze
    N1768 = "1768".freeze
    N1769 = "1769".freeze
    N1773 = "1773".freeze
    N1775 = "1775".freeze
    N1778 = "1778".freeze
    N1800 = "1800".freeze
    N1801 = "1801".freeze
    N1813 = "1813".freeze
    N1815 = "1815".freeze
    N1820 = "1820".freeze
    N1822 = "1822".freeze
    N1833 = "1833".freeze
    N1844 = "1844".freeze
    N1855 = "1855".freeze
    N1865 = "1865".freeze
    N1870 = "1870".freeze
    N1876 = "1876".freeze
    N1880 = "1880".freeze
    N1884 = "1884".freeze
    N1899 = "1899".freeze
    N1902 = "1902".freeze
    N1906 = "1906".freeze
    N1919 = "1919".freeze
    N1920 = "1920".freeze
    N1929 = "1929".freeze
    N1934 = "1934".freeze
    N1942 = "1942".freeze
    N1945 = "1945".freeze
    N1957 = "1957".freeze
    N1960 = "1960".freeze
    N1967 = "1967".freeze
    N1988 = "1988".freeze
    N1989 = "1989".freeze
    N2006 = "2006".freeze
    N2010 = "2010".freeze
    N2012 = "2012".freeze
    N2013 = "2013".freeze
    N2017 = "2017".freeze
    N2026 = "2026".freeze
    N2029 = "2029".freeze
    N2031 = "2031".freeze
    N2035 = "2035".freeze
    N2052 = "2052".freeze
    N2067 = "2067".freeze
    N2072 = "2072".freeze
    N2074 = "2074".freeze
    N2078 = "2078".freeze
    N2079 = "2079".freeze
    N2089 = "2089".freeze
    N2090 = "2090".freeze
    N2097 = "2097".freeze
    N2098 = "2098".freeze
    N2100 = "2100".freeze
    N2101 = "2101".freeze
    N2103 = "2103".freeze
    N2104 = "2104".freeze
    N2107 = "2107".freeze
    N2108 = "2108".freeze
    N2109 = "2109".freeze
    N2116 = "2116".freeze
    N2128 = "2128".freeze
    N2130 = "2130".freeze
    N2139 = "2139".freeze
    N2143 = "2143".freeze
    N2144 = "2144".freeze
    N2147 = "2147".freeze
    N2150 = "2150".freeze
    N2151 = "2151".freeze
    N2152 = "2152".freeze
    N2156 = "2156".freeze
    N2164 = "2164".freeze
    N2183 = "2183".freeze
    N2200 = "2200".freeze
    N2201 = "2201".freeze
    N2228 = "2228".freeze
    N2230 = "2230".freeze
    N2241 = "2241".freeze
    N2242 = "2242".freeze
    N2243 = "2243".freeze
    N2247 = "2247".freeze
    N2256 = "2256".freeze
    N2257 = "2257".freeze
    N2260 = "2260".freeze
    N2271 = "2271".freeze
    N2273 = "2273".freeze
    N2278 = "2278".freeze
    N2282 = "2282".freeze
    N2290 = "2290".freeze
    N2297 = "2297".freeze
    N2301 = "2301".freeze
    N2317 = "2317".freeze
    N2350 = "2350".freeze
    N2374 = "2374".freeze
    N2380 = "2380".freeze
    N2414 = "2414".freeze
    N2415 = "2415".freeze
    N2419 = "2419".freeze
    N2494 = "2494".freeze
    N2506 = "2506".freeze
    N2519 = "2519".freeze
    N2533 = "2533".freeze
    N2555 = "2555".freeze
    N2579 = "2579".freeze
    N2584 = "2584".freeze
    N2586 = "2586".freeze
    N2608 = "2608".freeze
    N2629 = "2629".freeze
    N2640 = "2640".freeze
    N2642 = "2642".freeze
    N2672 = "2672".freeze
    N2684 = "2684".freeze
    N2695 = "2695".freeze
    N2696 = "2696".freeze
    N2724 = "2724".freeze
    N2741 = "2741".freeze
    N2742 = "2742".freeze
    N2746 = "2746".freeze
    N2754 = "2754".freeze
    N2756 = "2756".freeze
    N2763 = "2763".freeze
    N2807 = "2807".freeze
    N2853 = "2853".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TestManf.constants.select { |c| TestManf::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TestManf" if constantValues.empty?
      value
    end
  end
end
