=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module DigitalCovidCertificateClient
  class TestManf
    N1833 = "1833".freeze
    N1232 = "1232".freeze
    N1468 = "1468".freeze
    N1304 = "1304".freeze
    N1822 = "1822".freeze
    N1815 = "1815".freeze
    N1736 = "1736".freeze
    N768 = "768".freeze
    N1654 = "1654".freeze
    N2010 = "2010".freeze
    N1906 = "1906".freeze
    N1870 = "1870".freeze
    N1331 = "1331".freeze
    N1484 = "1484".freeze
    N1223 = "1223".freeze
    N1236 = "1236".freeze
    N1173 = "1173".freeze
    N1919 = "1919".freeze
    N1225 = "1225".freeze
    N1375 = "1375".freeze
    N1244 = "1244".freeze
    N1253 = "1253".freeze
    N1144 = "1144".freeze
    N1747 = "1747".freeze
    N1360 = "1360".freeze
    N1437 = "1437".freeze
    N1256 = "1256".freeze
    N1363 = "1363".freeze
    N1365 = "1365".freeze
    N1844 = "1844".freeze
    N1215 = "1215".freeze
    N1392 = "1392".freeze
    N1767 = "1767".freeze
    N1263 = "1263".freeze
    N1333 = "1333".freeze
    N1764 = "1764".freeze
    N1266 = "1266".freeze
    N1267 = "1267".freeze
    N1268 = "1268".freeze
    N1180 = "1180".freeze
    N1190 = "1190".freeze
    N1481 = "1481".freeze
    N1162 = "1162".freeze
    N1420 = "1420".freeze
    N1199 = "1199".freeze
    N308 = "308".freeze
    N1271 = "1271".freeze
    N1341 = "1341".freeze
    N1097 = "1097".freeze
    N1606 = "1606".freeze
    N1604 = "1604".freeze
    N1489 = "1489".freeze
    N1490 = "1490".freeze
    N344 = "344".freeze
    N345 = "345".freeze
    N1319 = "1319".freeze
    N2017 = "2017".freeze
    N1769 = "1769".freeze
    N1574 = "1574".freeze
    N1218 = "1218".freeze
    N1114 = "1114".freeze
    N1466 = "1466".freeze
    N1934 = "1934".freeze
    N1443 = "1443".freeze
    N1246 = "1246".freeze
    N1763 = "1763".freeze
    N1278 = "1278".freeze
    N1456 = "1456".freeze
    N1884 = "1884".freeze
    N1296 = "1296".freeze
    N1295 = "1295".freeze
    N1343 = "1343".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TestManf.constants.select { |c| TestManf::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TestManf" if constantValues.empty?
      value
    end
  end
end
