=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module DigitalCovidCertificateClient
  class VaccineMahManf
    ORG_100001699 = "ORG-100001699".freeze
    ORG_100030215 = "ORG-100030215".freeze
    ORG_100001417 = "ORG-100001417".freeze
    ORG_100031184 = "ORG-100031184".freeze
    ORG_100006270 = "ORG-100006270".freeze
    ORG_100013793 = "ORG-100013793".freeze
    ORG_100020693 = "ORG-100020693".freeze
    ORG_100010771 = "ORG-100010771".freeze
    ORG_100024420 = "ORG-100024420".freeze
    ORG_100032020 = "ORG-100032020".freeze
    GAMALEYA_RESEARCH_INSTITUTE = "Gamaleya-Research-Institute".freeze
    VECTOR_INSTITUTE = "Vector-Institute".freeze
    SINOVAC_BIOTECH = "Sinovac-Biotech".freeze
    BHARAT_BIOTECH = "Bharat-Biotech".freeze
    ORG_100001981 = "ORG-100001981".freeze
    FIOCRUZ = "Fiocruz".freeze
    ORG_100007893 = "ORG-100007893".freeze
    CHUMAKOV_FEDERAL_SCIENTIFIC_CENTER = "Chumakov-Federal-Scientific-Center".freeze
    ORG_100023050 = "ORG-100023050".freeze
    CIGB = "CIGB".freeze
    SINOPHARM_WIBP = "Sinopharm-WIBP".freeze
    ORG_100033914 = "ORG-100033914".freeze
    ORG_100000788 = "ORG-100000788".freeze
    ORG_100036422 = "ORG-100036422".freeze
    INSTITUTO_BUTANTAN = "Instituto-Butantan".freeze
    NVSI = "NVSI".freeze
    YISHENG_BIOPHARMA = "Yisheng-Biopharma".freeze
    ORG_100026614 = "ORG-100026614".freeze
    ORG_100008549 = "ORG-100008549".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = VaccineMahManf.constants.select { |c| VaccineMahManf::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #VaccineMahManf" if constantValues.empty?
      value
    end
  end
end
