=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DigitalCovidCertificateClient::DiseaseAgentTargeted
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DigitalCovidCertificateClient::DiseaseAgentTargeted do
  let(:instance) { DigitalCovidCertificateClient::DiseaseAgentTargeted.new }

  describe 'test an instance of DiseaseAgentTargeted' do
    it 'should create an instance of DiseaseAgentTargeted' do
      expect(instance).to be_instance_of(DigitalCovidCertificateClient::DiseaseAgentTargeted)
    end
  end
end
