=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DigitalCovidCertificateClient::HTTPValidationError
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DigitalCovidCertificateClient::HTTPValidationError do
  let(:instance) { DigitalCovidCertificateClient::HTTPValidationError.new }

  describe 'test an instance of HTTPValidationError' do
    it 'should create an instance of HTTPValidationError' do
      expect(instance).to be_instance_of(DigitalCovidCertificateClient::HTTPValidationError)
    end
  end
  describe 'test attribute "detail"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
