=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for DigitalCovidCertificateClient::QRName
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe DigitalCovidCertificateClient::QRName do
  let(:instance) { DigitalCovidCertificateClient::QRName.new }

  describe 'test an instance of QRName' do
    it 'should create an instance of QRName' do
      expect(instance).to be_instance_of(DigitalCovidCertificateClient::QRName)
    end
  end
  describe 'test attribute "fn"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "gn"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "fnt"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "gnt"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
