=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module DigitalCovidCertificateClient
  class DiseaseAgentTargeted
    N840539006 = "840539006".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = DiseaseAgentTargeted.constants.select { |c| DiseaseAgentTargeted::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #DiseaseAgentTargeted" if constantValues.empty?
      value
    end
  end
end
