=begin
#Negative test certificate API

#API for generating negative certificates for covid tests

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.1

=end

require 'date'
require 'time'

module DigitalCovidCertificateClient
  class VaccineMahManf
    ORG_100001699 = "ORG-100001699".freeze
    ORG_100030215 = "ORG-100030215".freeze
    ORG_100001417 = "ORG-100001417".freeze
    ORG_100031184 = "ORG-100031184".freeze
    ORG_100006270 = "ORG-100006270".freeze
    ORG_100013793 = "ORG-100013793".freeze
    ORG_100020693 = "ORG-100020693".freeze
    ORG_100010771 = "ORG-100010771".freeze
    ORG_100024420 = "ORG-100024420".freeze
    ORG_100032020 = "ORG-100032020".freeze
    GAMALEYA_RESEARCH_INSTITUTE = "Gamaleya-Research-Institute".freeze
    VECTOR_INSTITUTE = "Vector-Institute".freeze
    SINOVAC_BIOTECH = "Sinovac-Biotech".freeze
    BHARAT_BIOTECH = "Bharat-Biotech".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = VaccineMahManf.constants.select { |c| VaccineMahManf::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #VaccineMahManf" if constantValues.empty?
      value
    end
  end
end
